// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Provides a Genkit flow for summarizing ad content using AI.
 *
 * - `summarizeAd`: A function that takes ad content as input and returns a short AI-generated summary.
 * - `SummarizeAdInput`: The input type for the `summarizeAd` function.
 * - `SummarizeAdOutput`: The return type for the `summarizeAd` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Define the input schema for the ad summarization flow.
const SummarizeAdInputSchema = z.object({
  adContent: z
    .string()
    .describe('The full text content of the ad that needs to be summarized.'),
});

// Define the TypeScript type for the input schema.
export type SummarizeAdInput = z.infer<typeof SummarizeAdInputSchema>;

// Define the output schema for the ad summarization flow.
const SummarizeAdOutputSchema = z.object({
  summary: z
    .string()
    .describe(
      'A short, AI-generated summary of the ad content, typically one sentence long.'
    ),
});

// Define the TypeScript type for the output schema.
export type SummarizeAdOutput = z.infer<typeof SummarizeAdOutputSchema>;

// Exported function to summarize ad content.
export async function summarizeAd(input: SummarizeAdInput): Promise<SummarizeAdOutput> {
  return summarizeAdFlow(input);
}

// Define the prompt for summarizing the ad content.
const summarizeAdPrompt = ai.definePrompt({
  name: 'summarizeAdPrompt',
  input: {schema: SummarizeAdInputSchema},
  output: {schema: SummarizeAdOutputSchema},
  prompt: `You are an AI assistant specializing in creating concise summaries of classified ads.

  Given the content of an ad, your task is to generate a single-sentence summary that captures the essence of the ad.

  Ad Content: {{{adContent}}}

  Summary:`, // Handlebars template to insert the ad content.
});

// Define the Genkit flow for summarizing ad content.
const summarizeAdFlow = ai.defineFlow(
  {
    name: 'summarizeAdFlow',
    inputSchema: SummarizeAdInputSchema,
    outputSchema: SummarizeAdOutputSchema,
  },
  async input => {
    // Call the prompt to generate the summary.
    const {output} = await summarizeAdPrompt(input);
    // Return the generated summary.
    return output!;
  }
);
